"""updated the metadata to be jsonb

Revision ID: 22c4182e4fa8
Revises: 04cae774c96e
Create Date: 2025-08-30 02:27:15.916834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22c4182e4fa8'
down_revision: Union[str, None] = '04cae774c96e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('collection_768_1_vector_idx', table_name='collection_768_1', postgresql_using='hnsw')
    op.drop_table('collection_768_1')
    op.alter_column('chunks', 'chunk_metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chunks', 'chunk_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_table('collection_768_1',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('vector', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.chunk_id'], name='collection_768_1_chunk_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='collection_768_1_pkey')
    )
    op.create_index('collection_768_1_vector_idx', 'collection_768_1', ['vector'], unique=False, postgresql_using='hnsw')
    # ### end Alembic commands ###
