from pydantic import BaseModel,Field,validator
from typing import Optional
from bson import ObjectId

class Project(BaseModel):

    _id : Optional[ObjectId] # this id is generated by mongodb when creating a new document and when i retrieve the document i get this id but when i create it i dont need to provide it
    project_id : str = Field(...,min_length=1)

    @validator('project_id')
    def project_id_validator(cls,value): # create custom validator for the project id ()
        if not value.isalnum():
            raise ValueError('Project id must be alphanumeric')
        return value

    class Config:
        arbitrary_types_allowed = True